### ISSUE TITLE
'+' symbol is causing error.

### ISSUE THREAD

**Issue by armm77** [gnustep/tools-packaging#6]
https://github.com/gnustep/tools-packaging/blob/894d612f3f7832bd3bf33839c83f3a3a084bfb18/cmd/deb-build-packages.sh#L209

**Comment by hmelder** [comment]
You should checkout the new branch: https://github.com/gnustep/tools-packaging/blob/pbuilder-scripts/

**Comment by hmelder** [comment]
Branch is merged into main
